---
- name: Does the Google apt file exist?
  command: test -f {{chrome_apt_file}}
  register: google_apt_exists
  ignore_errors: True
  when: ansible_os_family == "Debian"

- name: Add Google Chrome key
  become: True
  shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  when: ansible_os_family == "Debian" and google_apt_exists.rc == 1

- name: Add Google Chrome repo
  become: True
  copy: content="deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" dest={{chrome_apt_file}} owner=root group=root mode=644
  when: ansible_os_family == "Debian" and google_apt_exists.rc == 1

- name: Update apt cache
  become: True
  apt: update_cache=yes
  when: ansible_os_family == "Debian" and google_apt_exists.rc == 1

- name: Install Google Chrome
  become: True
  apt: pkg=google-chrome-stable state=installed
  when: ansible_os_family == "Debian"

# OSX
- name: Install Google Chrome
  homebrew_cask: pkg=google-chrome state=present
  when: ansible_os_family == "Darwin"
