---
- name: Does the Google apt file exist?
  script: install_chrome.sh
  when: ansible_os_family == "Debian"

# OSX
- name: Install Google Chrome
  homebrew_cask: name=google-chrome state=present
  when: ansible_os_family == "Darwin"
