---
- name: Install Conda
  script: install_conda.sh {{ conda_binary_url }} creates=/home/{{username}}/miniconda3
  when: ansible_os_family == "Debian"

# If you are afraid it is old
# conda update conda
# conda update anaconda
