---
- name: Install Docker repo
  become: true
  apt:
    pkg:
      - docker.io
      - docker-compose
  when: ansible_os_family == "Debian"

# Needed when on a subnet that docker uses by default. i.e. Schrodinger New York
#
#- name: Installing Tools
#  apt: name={{item}} state=present
#  become: true
#  with_items:
#    - bridge-utils
#    - apt-transport-https
#    - ca-certificates
#  when: ansible_os_family == "Debian"
#
#
#- name: Move Docker Configuration to non-standard subnet
#  become: true
#  copy: src=docker.conf dest=/etc/default/docker
#  when: ansible_os_family == "Debian"
#
#  # You might still need to copy over docker.service to /lib/systemd/system/docker.service
#  # It depends if docker has gotten its shit together to source /etc/default/docker
#- name: Update Docket Service File
#  become: true
#  copy: src=docker.service dest=/lib/systemd/system/docker.service
#  when: ansible_os_family == "Debian"
#
#- name: Delete old network bridge
#  become: true
#  script: docker_delete_network_bridge.sh
#  when: ansible_os_family == "Debian"
