---
- name: Add gimp ppa
  become: true
  apt_repository: repo='ppa:otto-kesselgulasch/gimp'
  when: ansible_os_family == "Debian"


- name: Apt-Get Update
  become: true
  apt: update_cache=yes
  when: ansible_os_family == "Debian"

- name: Install gimp
  become: true
  apt: name={{item}} force=yes state=present
  when: ansible_os_family == "Debian"
  with_items:
      - gimp
