---
- name: Apt-Get Update
  become: true
  apt: update_cache=yes
  when: ansible_os_family == "Debian"

- name: Installing golang
  apt: name={{item}} state=present
  become: true
  with_items:
    - golang
  when: ansible_os_family == "Debian"
