---

- name: Set seurat-users git prefs
  become: true
  become_user: jenkins
  script: set_git_prefs.sh /mnt/jenkins/workspace "Karl Leswing" "karl.leswing@schrodinger.com"

- name: make ~/.ssh/known_hosts owned by jenkins
  become: true
  file: path=/home/jenkins/.ssh/known_hosts owner=jenkins group=jenkins

- name: git pull
  become: true
  become_user: jenkins
  git: repo=ssh://pdx-git.schrodinger.com/var/git/repos/seurat.git dest=/mnt/jenkins/workspace update=yes version=master accept_hostkey=true force=yes
