---
- name: Apt-Get Update
  become: true
  apt: update_cache=yes
  when: ansible_os_family == "Debian"

- name: Install Latex
  become: true
  apt: name={{item}} force=yes state=present
  with_items:
    - texlive-full
    - texmaker
  when: ansible_os_family == "Debian"
