---
- name: ensure apt cache is up to date
  become: true
  apt: update_cache=yes cache_valid_time=3600
  when: ansible_os_family == "Debian"


- name: ensure packages are installed
  apt: name={{item}} state=present
  become: true
  when: ansible_os_family == "Debian"
  with_items:
    - monit

- name: Apply Monit Configurations
  become: true
  template: src=templates/monit.conf.j2 dest=/etc/monit/conf.d/ssh-logins
  when: ansible_os_family == "Debian"

- name: Apply Monit Configurations
  become: true
  template: src=templates/monitrc.j2 dest=/etc/monit/monitrc
  when: ansible_os_family == "Debian"

- name: Restart Monit with New Configurations
  become: true
  service: name=monit state=restarted
  when: ansible_os_family == "Debian"
