---
- name: Apt-Get Update
  become: true
  apt: update_cache=yes
  when: ansible_os_family == "Debian"

- name: Install node
  become: true
  apt: name={{item}} state=present
  with_items:
    - npm
    - nodejs
  when: ansible_os_family == "Debian"

- name: Install grunt cli
  become: true
  npm: name=grunt-cli global=yes
  when: ansible_os_family == "Debian"

- name: Install closure linter
  become: true
  command: pip install closure-linter
  when: ansible_os_family == "Debian"

# OSX
- name: Installing node
  homebrew: name={{item}} state=present
  with_items:
    - node
  when: ansible_os_family == "Darwin"
