---
- name: Apt-Get Update
  become: true
  apt: update_cache=yes
  when: ansible_os_family == "Debian"

- name: Install Pass
  become: true
  apt: name={{item}} force=yes state=present
  when: ansible_os_family == "Debian"
  with_items:
      - pass

# copy private.key to ./
# gpg --import private.key
# gpg --edit-key <key>
# trust
# 5 // I trust ultimately

# pass init "<key>
# pass git init
# pass git remote add origin repo
# pass git pull origin master
