---
- sudo: yes
  tasks:
  - name: ensure apt cache is up to date
    apt: update_cache=yes
  - name: ensure packages are installed
    apt: name={{item}}
    with_items:
        - postgresql
        - postgresql-contrib
        - postgresql-client
        - libpq-dev
        - python-psycopg2
        - pgadmin3
