- name: add group
  become: true
  group:
    name: timr
    state: present

- name: add user
  become: true
  user:
    state: present
    name: timr
    shell: /bin/bash
    password: "{{ 'password' | password_hash('sha512') }}"
    home: /home/timr
    groups: sudo,timr
