- name: add group
  become: true
  group:
    name: jenkins
    state: present

- name: add user
  become: true
  user:
    name: jenkins
    shell: /bin/bash
    password: "{{ 'password' | password_hash('sha512') }}"
    home: /var/lib/jenkins
    groups: sudo,jenkins
