- name: add group
  become: true
  group:
    name: qsar_smash
    state: present

- name: add user
  become: true
  user:
    name: qsar_smash
    shell: /bin/bash
    password: "{{ 'password' | password_hash('sha512') }}"
    home: /home/qsar_smash
    groups: sudo,qsar_smash
