- name: add group
  become: true
  group:
    name: "{{ username }}"
    state: present

- name: add user
  become: true
  user:
    state: present
    name: "{{ username }}"
    shell: /bin/bash
    password: "{{ 'password' | password_hash('sha512') }}"
    home: "/home/{{ username }}"
    groups: "sudo,{{ username }}"
