---
- name: Installing vims
  become: true
  apt: name={{item}} state=present
  when: ansible_os_family == "Debian"
  with_items:
    - vim
    - vim-gtk
    - curl

- name: Set vim as default editor (Ubuntu)
  become: true
  command: update-alternatives --set editor /usr/bin/vim.basic
  when: ansible_os_family == "Debian"

- name: vimrc movement
  copy: src=vimrc dest=/home/{{username}}/.vimrc
  when: ansible_os_family == "Debian"

- name: vimrc movement
  copy: src=vimrc dest=/home/{{username}}/.ideavimrc
  when: ansible_os_family == "Debian"

- name: install pathogen
  script: install_pathogen.sh creates=/home/{{username}}/.vim/autoload/pathogen.vim
  when: ansible_os_family == "Debian"

- name: install solarized
  script: install_solarized_vim.sh creates=/home/{{username}}/.vim/colors/solarized.vim
  when: ansible_os_family == "Debian"

- name: install NERDTree
  script: install_nerdtree.sh creates=/home/{{username}}/.vim/bundle/nerdtree
  when: ansible_os_family == "Debian"

# OSX
- name: Installing Macvim
  homebrew_cask: name={{item}} state=present
  with_items:
    - macvim
  when: ansible_os_family == "Darwin"

- name: vimrc movement
  copy: src=vimrc dest=/Users/{{username}}/.vimrc
  when: ansible_os_family == "Darwin"

- name: install pathogen
  script: install_pathogen.sh creates=/Users/{{username}}/.vim/autoload/pathogen.vim
  when: ansible_os_family == "Darwin"

- name: install solarized
  script: install_solarized_vim.sh creates=/Users/{{username}}/.vim/colors/solarized.vim
  when: ansible_os_family == "Darwin"

- name: install NERDTree
  script: install_nerdtree.sh creates=/Users/{{username}}/.vim/bundle/nerdtree
  when: ansible_os_family == "Darwin"

