---
- name: Installing vims
  sudo: true
  apt: name={{item}} state=present
  with_items:
    - vim
    - vim-gnome
    - curl

- name: Set vim as default editor (Ubuntu)
  sudo: true
  command: update-alternatives --set editor /usr/bin/vim.basic

- name: vimrc movement
  copy: src=vimrc dest=/home/{{username}}/.vimrc

- name: install pathogen
  script: install_pathogen.sh creates=/home/{{username}}/.vim/autoload/pathogen.vim

- name: install solarized
  script: install_solarized_vim.sh creates=/home/{{username}}/.vim/colors/solarized.vim

- name: install NERDTree
  script: install_nerdtree.sh creates=/home/{{username}}/.vim/bundle/nerdtree

- name: install syntastic
  script: install_syntastic.sh creates=/home/{{username}}/.vim/bundle/syntastic
