---
- name: Apt-Get Update
  become: true
  apt: update_cache=yes
  when: ansible_os_family == "Debian"

- name: Install VLC
  become: true
  apt: name={{item}} force=yes state=present
  with_items:
    - vlc
    - browser-plugin-vlc
    - libavcodec-extra
  when: ansible_os_family == "Debian"

# OSX
- name: Installing VLC
  homebrew_cask: name={{item}} state=present
  with_items:
    - vlc
  when: ansible_os_family == "Darwin"
