---
- name: Apt-Get Update
  sudo: true
  apt: update_cache=yes

- name: Install VLC
  sudo: true
  apt: name={{item}} force=yes state=present
  with_items:
    - vlc
    - browser-plugin-vlc
    - libavcodec-extra

