---

- name: Bootstrapping developer environment
  hosts: all

  tasks:

  - name: Determining username
    action: shell whoami
    register: whoami
    sudo: False

  - name: Installing zsh, vim, git, tmux, etc.
    action: yum pkg=$item state=latest
    with_items:
    - zsh
    - vim-enhanced
    - git
    - tmux
    - htop

  - name: Changing the default shell to zsh
    action: user shell=/bin/zsh user=${whoami.stdout}

  - name: Backing up existing ~/.zshrc
    action: shell if [ -f ~/.zshrc ]; then mv ~/.zshrc{,.orig}; fi

  - name: Installing oh-my-zsh (https://github.com/robbyrussell/oh-my-zsh)
    action: git repo=https://github.com/robbyrussell/oh-my-zsh dest=~/.oh-my-zsh

  - name: Creating new ~/.zshrc
    action: shell cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc
