---
  - name: Apt-Get Update
    sudo: true
    apt: update_cache=yes

  - name: Installing utilities
    apt: name={{item}} state=present
    sudo: true
    with_items:
      - tmux
      - autojump
      - zsh
      - terminator
      - cowsay
      - fortune
      - libreadline5
      - libreadline6
      - p7zip-full
      - build-essential
      - ant
      - python-dev
      - python-virtualenv
      - python-pip
      - xclip
      - sqlite3
      - htop
      - mercurial

  - name: Install matplotlib build deps
    sudo: true
    apt: name=python-matplotlib state=build-dep

  - name: tmux movement
    copy: src=tmux.conf dest=/home/{{username}}/.tmux.conf

  - name: oh_my_zsh install
    script: install_oh_my_zsh.sh creates=/home/{{username}}/.oh-my-zsh/README.markdown

  - name: zshrc movement
    copy: src=zsh.rc dest=/home/{{username}}/.zshrc backup=yes

  - name: install zsh-syntax-highlighting
    git: repo=https://github.com/zsh-users/zsh-syntax-highlighting.git dest=/home/{{username}}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

  - name: terminator solarized
    script: set_terminator_solarized.sh
